import type { MarketProfile } from "@/lib/market-matching/types";

/** Modelované atributy trhů (0–100). Vyšší = atraktivnější na ose (u rizika = bezpečnější). */
export const MARKET_PROFILES: MarketProfile[] = [
  {
    id: "cz",
    name: "Česká republika",
    typicalMinCapitalCzk: 400_000,
    typicalEntryCapitalCzk: 1_200_000,
    attributes: {
      required_capital: 62,
      financing_availability: 92,
      target_yield: 38,
      volatility_risk: 78,
      ownership_security: 94,
      liquidity: 82,
      currency_risk: 98,
      regulation: 88,
      investment_horizon: 72,
      intended_use: 70,
    },
    financingOptions: [
      "Hypotéka české banky (živé sazby)",
      "Americká hypotéka / refinancování",
      "Hotovost",
    ],
    topRisks: [
      "Nižší hrubý yield oproti exotickým trhům",
      "Citlivost na sazby ČNB a DSTI praxi bank",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "Domácí právo, CZK, nejširší hypoteční nabídka.",
  },
  {
    id: "sk",
    name: "Slovensko",
    typicalMinCapitalCzk: 350_000,
    typicalEntryCapitalCzk: 1_000_000,
    attributes: {
      required_capital: 65,
      financing_availability: 72,
      target_yield: 42,
      volatility_risk: 74,
      ownership_security: 90,
      liquidity: 70,
      currency_risk: 85,
      regulation: 86,
      investment_horizon: 70,
      intended_use: 68,
    },
    financingOptions: [
      "Lokální hypotéka (sazby na vyžádání)",
      "České zajištění (americká hypotéka)",
      "Hotovost",
    ],
    topRisks: [
      "Nižší likvidita mimo Bratislavu",
      "Lokální sazby nejsou live na platformě",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "EUR + blízký právní rámec EU.",
  },
  {
    id: "ae",
    name: "SAE (Dubaj)",
    typicalMinCapitalCzk: 500_000,
    typicalEntryCapitalCzk: 1_500_000,
    attributes: {
      required_capital: 48,
      financing_availability: 86,
      target_yield: 78,
      volatility_risk: 42,
      ownership_security: 72,
      liquidity: 68,
      currency_risk: 48,
      regulation: 58,
      investment_horizon: 62,
      intended_use: 82,
    },
    financingOptions: [
      "Developer payment plan (off-plan)",
      "České zajištění (americká hypotéka)",
      "Hotovost",
    ],
    topRisks: [
      "Volatilita off-plan nabídky a service charges",
      "Měnové a regulatorní riziko pro nerezidenty",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "Vysoký modelový yield; developer plány ≠ bankovní hypotéka.",
  },
  {
    id: "es",
    name: "Španělsko",
    typicalMinCapitalCzk: 600_000,
    typicalEntryCapitalCzk: 1_800_000,
    attributes: {
      required_capital: 45,
      financing_availability: 58,
      target_yield: 55,
      volatility_risk: 62,
      ownership_security: 84,
      liquidity: 72,
      currency_risk: 72,
      regulation: 78,
      investment_horizon: 68,
      intended_use: 88,
    },
    financingOptions: [
      "Hypotéka pro nerezidenty (individuálně)",
      "České zajištění",
      "Hotovost",
    ],
    topRisks: [
      "Regulace krátkodobých pronájmů dle lokality",
      "Financování nerezidentů často nižší LTV",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "EU rámec; silný lifestyle + yield mix.",
  },
  {
    id: "it",
    name: "Itálie",
    typicalMinCapitalCzk: 550_000,
    typicalEntryCapitalCzk: 1_600_000,
    attributes: {
      required_capital: 48,
      financing_availability: 52,
      target_yield: 50,
      volatility_risk: 60,
      ownership_security: 82,
      liquidity: 58,
      currency_risk: 72,
      regulation: 74,
      investment_horizon: 65,
      intended_use: 80,
    },
    financingOptions: [
      "Lokální financování (individuálně / na vyžádání)",
      "České zajištění",
      "Hotovost",
    ],
    topRisks: [
      "Delší právní proces koupě",
      "Silné regionální rozdíly sever/jih",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "Stabilní vlastnictví; likvidita mimo hotspots nižší.",
  },
  {
    id: "hr",
    name: "Chorvatsko",
    typicalMinCapitalCzk: 500_000,
    typicalEntryCapitalCzk: 1_400_000,
    attributes: {
      required_capital: 52,
      financing_availability: 48,
      target_yield: 58,
      volatility_risk: 58,
      ownership_security: 80,
      liquidity: 55,
      currency_risk: 78,
      regulation: 72,
      investment_horizon: 64,
      intended_use: 86,
    },
    financingOptions: [
      "České zajištění",
      "Hotovost",
      "Lokální úvěr (omezeně / individuálně)",
    ],
    topRisks: [
      "Sezónnost přímořských výnosů",
      "Omezenější lokální financování pro cizince",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "Schengen + EUR; silný částečný vlastní užitek.",
  },
  {
    id: "id",
    name: "Bali (Indonésie)",
    typicalMinCapitalCzk: 700_000,
    typicalEntryCapitalCzk: 2_000_000,
    attributes: {
      required_capital: 40,
      financing_availability: 28,
      target_yield: 92,
      volatility_risk: 32,
      ownership_security: 38,
      liquidity: 42,
      currency_risk: 28,
      regulation: 35,
      investment_horizon: 48,
      intended_use: 75,
    },
    financingOptions: [
      "Hotovost",
      "Developer payment plan (bez lokální hypotéky pro cizince)",
      "České zajištění (odděleně od bali aktiva)",
    ],
    topRisks: [
      "Leasehold / struktura vlastnictví pro cizince",
      "Vysoké měnové a provozní riziko",
      "Lokální hypotéka pro cizince prakticky nedostupná",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "Nejvyšší modelový yield; kapitálově a právně náročné.",
  },
  {
    id: "sa",
    name: "Saúdská Arábie",
    typicalMinCapitalCzk: 800_000,
    typicalEntryCapitalCzk: 2_500_000,
    attributes: {
      required_capital: 35,
      financing_availability: 40,
      target_yield: 60,
      volatility_risk: 45,
      ownership_security: 55,
      liquidity: 40,
      currency_risk: 42,
      regulation: 48,
      investment_horizon: 55,
      intended_use: 58,
    },
    financingOptions: [
      "Hotovost",
      "České zajištění",
      "Lokální produkty — ověřit individuálně (Vision 2030)",
    ],
    topRisks: [
      "Podmínky vlastnictví pro cizince se vyvíjejí",
      "Nižší likvidita a méně historických dat",
    ],
    dataStatus: "MODELLED",
    lastReviewedAt: "2026-07-01",
    notes: "Emerging opportunity; vyžaduje individuální due diligence.",
  },
];

export const WEIGHTS_VERSION = "2026-07-market-matching-v1";
