import type { MarketProfile } from "@/lib/market-matching/types";

/**
 * Modelované atributy trhů (0–100).
 * Vyšší = atraktivnější (u complexity = nižší složitost pro investora).
 * VERZE: v2 — tax + operational complexity (PROMPT 16).
 */
export const MARKET_PROFILES: MarketProfile[] = [
  {
    id: "cz",
    name: "Česká republika",
    typicalMinCapitalCzk: 400_000,
    typicalEntryCapitalCzk: 1_200_000,
    attributes: {
      capital_fit: 62,
      financing_fit: 92,
      yield_potential: 38,
      ownership_accessibility: 94,
      liquidity: 82,
      fx_risk: 98,
      regulatory_complexity: 88,
      tax_complexity: 82,
      operational_complexity: 80,
      user_goal_fit: 70,
    },
    financingOptions: [
      "Hypotéka české banky (živé sazby)",
      "Americká hypotéka / refinancování",
      "Hotovost",
    ],
    topRisks: [
      "Nižší hrubý yield oproti exotickým trhům",
      "Citlivost na sazby ČNB a DSTI praxi bank",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "Domácí právo, CZK, nejširší hypoteční nabídka.",
  },
  {
    id: "sk",
    name: "Slovensko",
    typicalMinCapitalCzk: 350_000,
    typicalEntryCapitalCzk: 1_000_000,
    attributes: {
      capital_fit: 65,
      financing_fit: 72,
      yield_potential: 42,
      ownership_accessibility: 90,
      liquidity: 70,
      fx_risk: 85,
      regulatory_complexity: 86,
      tax_complexity: 78,
      operational_complexity: 74,
      user_goal_fit: 68,
    },
    financingOptions: [
      "Lokální hypotéka (sazby na vyžádání)",
      "České zajištění (americká hypotéka)",
      "Hotovost",
    ],
    topRisks: [
      "Nižší likvidita mimo Bratislavu",
      "Lokální sazby nejsou v aplikaci v reálném čase",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "EUR + blízký právní rámec EU.",
  },
  {
    id: "ae",
    name: "SAE (Dubaj)",
    typicalMinCapitalCzk: 500_000,
    typicalEntryCapitalCzk: 1_500_000,
    attributes: {
      capital_fit: 48,
      financing_fit: 86,
      yield_potential: 78,
      ownership_accessibility: 72,
      liquidity: 68,
      fx_risk: 48,
      regulatory_complexity: 58,
      tax_complexity: 68,
      operational_complexity: 45,
      user_goal_fit: 82,
    },
    financingOptions: [
      "Platební plán developera (ve výstavbě, off-plan)",
      "České zajištění (americká hypotéka)",
      "Hotovost",
    ],
    topRisks: [
      "Volatilita nabídky ve výstavbě a provozních poplatků",
      "Měnové a regulatorní riziko pro nerezidenty",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "Vysoký modelový yield; developer plány ≠ bankovní hypotéka.",
  },
  {
    id: "es",
    name: "Španělsko",
    typicalMinCapitalCzk: 600_000,
    typicalEntryCapitalCzk: 1_800_000,
    attributes: {
      capital_fit: 45,
      financing_fit: 58,
      yield_potential: 55,
      ownership_accessibility: 84,
      liquidity: 72,
      fx_risk: 72,
      regulatory_complexity: 78,
      tax_complexity: 55,
      operational_complexity: 62,
      user_goal_fit: 88,
    },
    financingOptions: [
      "Hypotéka pro nerezidenty (individuálně)",
      "České zajištění",
      "Hotovost",
    ],
    topRisks: [
      "Regulace krátkodobých pronájmů dle lokality",
      "Financování nerezidentů často nižší LTV",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "EU rámec; silný mix bydlení + výnos.",
  },
  {
    id: "it",
    name: "Itálie",
    typicalMinCapitalCzk: 550_000,
    typicalEntryCapitalCzk: 1_600_000,
    attributes: {
      capital_fit: 48,
      financing_fit: 52,
      yield_potential: 50,
      ownership_accessibility: 82,
      liquidity: 58,
      fx_risk: 72,
      regulatory_complexity: 74,
      tax_complexity: 48,
      operational_complexity: 55,
      user_goal_fit: 80,
    },
    financingOptions: [
      "Lokální financování (individuálně / na vyžádání)",
      "České zajištění",
      "Hotovost",
    ],
    topRisks: [
      "Delší právní proces koupě",
      "Silné regionální rozdíly sever/jih",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "Stabilní vlastnictví; likvidita mimo hotspots nižší.",
  },
  {
    id: "hr",
    name: "Chorvatsko",
    typicalMinCapitalCzk: 500_000,
    typicalEntryCapitalCzk: 1_400_000,
    attributes: {
      capital_fit: 52,
      financing_fit: 48,
      yield_potential: 58,
      ownership_accessibility: 80,
      liquidity: 55,
      fx_risk: 78,
      regulatory_complexity: 72,
      tax_complexity: 58,
      operational_complexity: 52,
      user_goal_fit: 86,
    },
    financingOptions: [
      "České zajištění",
      "Hotovost",
      "Lokální úvěr (omezeně / individuálně)",
    ],
    topRisks: [
      "Sezónnost přímořských výnosů",
      "Omezenější lokální financování pro cizince",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "Schengen + EUR; silný částečný vlastní užitek.",
  },
  {
    id: "id",
    name: "Bali (Indonésie)",
    typicalMinCapitalCzk: 700_000,
    typicalEntryCapitalCzk: 2_000_000,
    attributes: {
      capital_fit: 40,
      financing_fit: 28,
      yield_potential: 92,
      ownership_accessibility: 38,
      liquidity: 42,
      fx_risk: 28,
      regulatory_complexity: 35,
      tax_complexity: 32,
      operational_complexity: 28,
      user_goal_fit: 75,
    },
    financingOptions: [
      "Hotovost",
      "Platební plán developera (bez lokální hypotéky pro cizince)",
      "České zajištění (odděleně od bali aktiva)",
    ],
    topRisks: [
      "Leasehold / struktura vlastnictví pro cizince",
      "Vysoké měnové a provozní riziko",
      "Lokální hypotéka pro cizince prakticky nedostupná",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "Nejvyšší modelový yield; kapitálově a právně náročné.",
  },
  {
    id: "sa",
    name: "Saúdská Arábie",
    typicalMinCapitalCzk: 800_000,
    typicalEntryCapitalCzk: 2_500_000,
    attributes: {
      capital_fit: 35,
      financing_fit: 40,
      yield_potential: 60,
      ownership_accessibility: 55,
      liquidity: 40,
      fx_risk: 42,
      regulatory_complexity: 48,
      tax_complexity: 52,
      operational_complexity: 40,
      user_goal_fit: 58,
    },
    financingOptions: [
      "Hotovost",
      "České zajištění",
      "Lokální produkty — ověřit individuálně (Vision 2030)",
    ],
    topRisks: [
      "Podmínky vlastnictví pro cizince se vyvíjejí",
      "Nižší likvidita a méně historických dat",
    ],
    dataStatus: "MODEL",
    lastReviewedAt: "2026-07-01",
    notes: "Rozvíjející se trh; vyžaduje individuální prověrku nemovitosti.",
  },
];

/** Bump při změně vah nebo dimenzí — UI a audit. */
export const WEIGHTS_VERSION = "2026-07-investment-passport-v2";
