export {
  getOperatorIdentity,
  formatOperatorAddress,
  formatOperatorAddressCompact,
  formatOperatorRegisterLine,
  operatorDisplayName,
  isPaidAnalysisCommerciallyAvailable,
  type OperatorIdentity,
} from "@/lib/legal/operator";
export {
  getLegalIdentityConfig,
  isLegalIdentityComplete,
  isLegalTextReviewed,
  mustEnforceLegalIdentityForLeadCollection,
  LEGAL_IDENTITY_INCOMPLETE_PUBLIC_MESSAGE,
  LEGAL_LEAD_BLOCKED_PUBLIC_MESSAGE,
  getLegalDevIncompleteNotice,
  legalOperator,
  projectFounder,
  financialPartner,
  formatCommercialRegisterLine,
  formatCompactOfficeAddress,
} from "@/config/legal";
export {
  PROCESSING_ROLES,
  REGULATED_BOUNDARIES,
  LEGAL_INTERNAL_REVIEW_NOTE,
  LAWYER_REVIEW_NOTICE,
  getPublicProcessingRoles,
  getConditionalProcessingRoles,
} from "@/lib/legal/roles";
export {
  CONSENT_POLICY_VERSION,
  COOKIE_POLICY_VERSION,
  TERMS_VERSION,
  PAID_ANALYSIS_TERMS_VERSION,
  formatPolicyVersionDateCs,
  ANALYTICS_LEGAL_BASIS,
  ENQUIRY_PROCESSING_LEGAL_BASIS,
  CONSENT_PURPOSES,
  PARTNER_TRANSFER_SCOPE_LABELS,
  buildPartnerTransferCheckboxLabel,
  buildPrivacyProcessingCheckboxLabel,
  buildEnquiryPrivacyNotice,
  buildConsentContextSummary,
  isThirdPartyTransferActive,
  type ConsentPurposeId,
  type PartnerTransferScope,
} from "@/lib/legal/consent-versions";
export {
  getCookieInventory,
  getPublicCookieTableRows,
  getCookiePolicyDeploymentNotes,
  isGoogleAnalyticsConfigured,
  isMetaPixelScriptActive,
  COOKIE_CATEGORY_LABEL_CS,
  type CookieInventoryRow,
  type CookieCategory,
} from "@/lib/legal/cookie-inventory";
export {
  privacyRetention,
  buildPublicRetentionSummary,
  computeEnquiryRetentionUntil,
  addMonths,
  addDays,
  type PrivacyRetentionConfig,
} from "@/lib/legal/privacy-retention";
export { getPaidAnalysisTerms } from "@/lib/legal/paid-analysis-terms";
export {
  getMortgagePartners,
  getPrimaryMortgagePartner,
  partnerPublicDisplayName,
  isMortgagePartnerIdentityVerified,
  isMortgagePartnerHandoffReady,
  partnerJerrsPublicLabel,
  auditPartnerConfig,
  COMPENSATION_DISCLOSURE,
  type MortgagePartner,
  type MortgagePartnerJerrsStatus,
} from "@/lib/legal/partner-config";
export {
  collectLegalProductionIssues,
  assertLegalProductionGate,
  canAcceptPersonalLeads,
  PUBLIC_STAGING_PHRASES,
} from "@/lib/legal/production-guard";
export {
  buildLeadFormIntakeDisclosure,
  buildRegulatoryPlatformBlock,
  CALCULATOR_DISCLAIMER,
  PLATFORM_NEUTRAL_FALLBACK,
  containsPublicForbiddenPlaceholder,
  collectPublicRegulatoryStrings,
  getCooperationWordingNeutral,
  getPlatformWordingNeutral,
  isPartnerConfigPubliclyVerified,
  BANK_RATE_PAYMENT_NOTE,
  getJerrsRegistryUrl,
  getLastLegalReviewLine,
  getRegulatedBoundaryStatements,
  getRegulatoryFooterLine,
  RATES_DISCLAIMER,
  rt,
  resolveIntermediarySubject,
  JERRS_REGISTRY_INTRO_URL,
  CNB_INVESTMENT_RECOMMENDATION_TITLE,
  CNB_OWNER_OCCUPIED_TITLE,
  CNB_INVESTMENT_RECOMMENDATION_BODY,
  CNB_OWNER_OCCUPIED_BODY,
  CNB_PURPOSE_DISTINCTION,
  type IntermediarySubject,
  type RegulatoryPlatformBlock,
} from "@/lib/legal/regulatory-texts";
export {
  getValidatedPartnerEnv,
  isValidJerrsRegistryUrl,
  validatePartnerEnv,
  type ValidatedPartnerEnv,
} from "@/lib/legal/partner-env-validation";
export {
  toPartnerVerification,
  getPrimaryPartnerVerification,
  canUseStrongPartnerTrustClaims,
  getPartnerClaimLabels,
  type PartnerVerification,
  type PartnerVerificationStatus,
} from "@/lib/partners/verification";
